### ISSUE TITLE
Add Deutsche Bahn/German Railways Long-Distance Trains GTFS Feed

### ISSUE THREAD

**Issue by fredlockheed** [OpenMobilityData/OpenMobilityData-Public#106]
Deutsche Bahn (German Railways) provide API access to the timetable of their long-distance trains under CC BY 4.0:
http://data.deutschebahn.com/apis/fahrplan/

I have generated a GTFS feed based on their timetable:
https://github.com/fredlockheed/db-fv-gtfs

This is legal under their CC BY 4.0 license.

**Comment by benjaminburzan** [comment]
Hey @HendX will this API be added to TransitFeeds?
Thanks!

**Comment by joriswu** [comment]
+1. This feed is quite valuable for overall public transport connectivity in Europe.

**Comment by HendX** [comment]
I've added this here: http://transitfeeds.com/p/deutsche-bahn

Is it possible for there to be a static URL? The URL I'm using has 2017 hard-coded into it (`https://github.com/fredlockheed/db-fv-gtfs/releases/download/2017.0.0/2017.zip`), so presumably this will change next year.

**Comment by canales** [comment]
@fredlockheed We'd like to switch to this URL, https://github.com/fredlockheed/db-fv-gtfs/releases/download/latest/db-fv-gtfs.zip which is in your respository, instead of the 2017 hard-coded one that Quentin mentions above, however it is not working. Could you check this so that we can switch to that one?
