### ISSUE TITLE
GTFS Piemonte

### ISSUE THREAD

**Issue by stebazzi** [OpenMobilityData/OpenMobilityData-Public#189]
Please Add these of Region Piedmont (Piemonte in italian): 

http://www.dati.piemonte.it/catalogodati/scarica.html?idallegato=1098 (for the railways)
http://www.dati.piemonte.it/catalogodati/scarica.html?idallegato=1097 (for the buses)

Many thanks

**Comment by fede843** [comment]
Hi again. This sources should replace #122 right? I noticed buses source here contains a bigger number of operators. Do this source should replace https://transitfeeds.com/p/gruppo-torinese-trasporti/51 too? I see this source contains several GTT operators, but I'm not sure if they represent the same.

It's sad to hear transitfeeds is "on pause" since some months ago.

Cheers!
