### ISSUE TITLE
Fix feed url: NZ Intercity GTFS not updating

### ISSUE THREAD

**Issue by vblyth** [OpenMobilityData/OpenMobilityData-Public#483]
NZ Intercity GTFS stopped updating in July 2019.

URL on OpenMobilityData: 
https://transitfeeds.com/p/intercity-group/744

Please fix this.

**Comment by thlaegler** [comment]
Hi Verity,
since InterCity doesn't publish their GTFS data anymore, you could workaround this by fetching the trip data from their (inofficial?) API: `https://www.intercity.co.nz/book-a-trip/getServiceTimetable/<TripID>`
Looks like each Route has exactly one Trip (means: Trip ID = Route ID). The Trip IDs haven't changed much since the last published GTFS file from 2019, so you can use those Trip IDs in the above request. To get newer/missing Trips you could follow the attribute "coachTransfers" from the above response.
Cheers 👋

**Comment by vblyth** [comment]
Thanks Thomas! We'll give that a try. Hope you're going well. 👍
