### ISSUE TITLE
San Joaquin GTFS - need transfers.txt

### ISSUE THREAD

**Issue by gregforbes** [OpenMobilityData/OpenMobilityData-Public#499]
I'm looking at the following link:

https://transitfeeds.com/p/san-joaquin-rtd/347/latest

I can't find the "transfers.txt" anywhere, but I need to to analyze transit routes. When analyzing transit routes with transfers, I get transit times that are inconsistent with the true behavior of the San Joaquin transit system.

How can I get this file or have the link be updated? Thanks!

**Comment by dudebrains01** [comment]
It could be that San Joaquin RTD doesn't publish transfers.txt

It's an optional file.

**Comment by gregforbes** [comment]
They don't, but shouldn't they? Excuse me if this is a strange question. The thing is that I'm testing my transit algorithm with results from Google Maps. I'm using a GTFS feed from another Northern California transit authority which does have this the transfers.txt, and its results are consistent with Google Maps. However, I get inconsistent results with the San Joaquin GTFS when transfers are involved.

Could it be possible that Google Maps has the San Joaquin transfers.txt file? Why is there a discrepancy between GTFS feeds that do and do not have the transfers.txt?

Thank you for your help and patience.

**Comment by dudebrains01** [comment]
It does happen that some transit agencies have a seperate GTFS feed for Google maps, because Google has stricter requirements for data quality. You should maybe send an email to RTD to get some more info.

Keep in mind that the transfers file is optional, so including it is to the agency's discretion.

This may sound crazy, but you could also create your own transfers.txt file by looking at Google Maps and taking note of the discrepancies with your algorithm, and placing the transfers Google Maps suggests into a transfers.txt file, although that can get very complicated very fast.

Hope this helps!
